services:
  navidrome:
    image: deluan/navidrome:latest
    environment:
      - ND_EXTAUTH_TRUSTEDSOURCES=0.0.0.0/0
      - ND_ENABLEINSIGHTSCOLLECTOR=false
    volumes:
      - /messier/apps/navidrome/music:/music:ro
      - /messier/apps/navidrome/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.allowNonRunning=true"
      - "traefik.http.routers.navidrome-public.rule=Host(`music.${DOMAIN}`) && PathPrefix(`/rest/`)"
      - "traefik.http.routers.navidrome-public.entrypoints=https"
      - "traefik.http.routers.navidrome-public.tls.certresolver=${CERTRESOLVER:+${CERTRESOLVER}}"
      - "traefik.http.routers.navidrome-public.service=navidrome"
      - "traefik.http.routers.navidrome-public.middlewares=secure-headers@file"
      - "traefik.http.routers.navidrome-public.priority=10"
      - "traefik.http.routers.navidrome.rule=Host(`music.${DOMAIN}`)"
      - "traefik.http.routers.navidrome.entrypoints=https"
      - "traefik.http.routers.navidrome.tls.certresolver=${CERTRESOLVER:+${CERTRESOLVER}}"
      - "traefik.http.routers.navidrome.service=navidrome"
      - "traefik.http.routers.navidrome.middlewares=secure-headers@file,authelia@file"
      - "traefik.http.routers.navidrome.priority=1"
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"
    networks:
      - virgo
    restart: unless-stopped

networks:
  virgo:
    external: true
