http:
  serversTransports:
    insecure-transport:
      insecureSkipVerify: true
  middlewares:
    default-ratelimit:
      rateLimit:
        average: 100
        burst: 120
        period: 1s
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    secure-headers:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        contentTypeNosniff: true
        browserXssFilter: true
        customRequestHeaders:
          x-forwarded-proto: https
        customResponseHeaders:
          access-control-allow-origin: "*"
          access-control-allow-methods: "GET,OPTIONS,PUT"
          access-control-allow-headers: "authorization,content-type"
          server: ""
          x-powered-by: ""
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/authz/forward-auth?https://auth.`{{ env `DOMAIN` }}`"
        trustForwardHeader: true
        authResponseHeaders: "Remote-User,Remote-Groups,Remote-Name,Remote-Email"

tls:
  options:
    default:
      minVersion: VersionTLS13
